project:
  type: website
  output-dir: docs

website:
  title: "Jasmine's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About me"
      - href: portfolio-project/data-project.qmd 
        text: "Project: MediCal Data"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

