---
title: "Project: MediCal Eligibility Between Ethncities"
format: html
execute: 
  echo: false
  warning: false
  message: false
embed-resources: true
---

```{r}
#| label: setup
#| include: false
library(tidyverse)
```

## Data Description

Here is a description of my data and a link to the source embded here with references.

## Data Cleaning

Here I describe in plain speak what I did to clean the data. Do not show code or use technical terms. I want to be able to read this and understand what I did.


## Visualzation 1

Here is a description of the first visualization. I want to describe what the visualization shows to a general audience. I do not want to see any code or technical terms. I want to be able to read this and understand what the visualization shows. I also want to see a caption and alt text for the visualization. The caption should be a short description of the visualization and the alt text should be a longer description of the visualization. The alt text should be descriptive enough that someone who is blind could understand what the visualization shows.


## Visualization 2

Here is a description of the second visualization. I want to describe what the visualization shows to a general audience. I do not want to see any code or technical terms. I want to be able to read this and understand what the visualization shows. I also want to see a caption and alt text for the visualization. The caption should be a short description of the visualization and the alt text should be a longer description of the visualization. The alt text should be descriptive enough that someone who is blind could understand what the visualization shows.
